name: taskapp
publish_to: none
description: Project Task App DelandApps
environment: 
  sdk: '>=3.3.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get_cli: ^1.8.1
  google_fonts: ^4.0.4
  dio: 5.4.0
  pretty_dio_logger: ^1.3.1
  get_storage: ^2.1.1
  get: 4.6.6
  flutter: 
    sdk: flutter
  equatable: ^2.0.5
  flutter_easyloading: ^3.0.5
  dotted_border: ^2.1.0
  step_progress_indicator: ^1.0.2

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

