name: taskapp
description: "Project Task App DelandApps"
publish_to: 'none' 

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get_cli: ^1.8.1
  google_fonts: ^4.0.4
  get: 4.6.6
  dio: 5.4.0 # Library untuk http connection
  pretty_dio_logger: ^1.3.1 # Logging Http connection
  get_storage: ^2.1.1 # Untuk get storage
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true